// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/error22_einval.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class Error22EinvalBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Error22EinvalBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Error22EinvalBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// A very short-lived native function.
  ///
  /// For very short-lived functions, it is fine to call them on the main isolate.
  /// They will block the Dart execution while running the native function, so
  /// only do this for native functions which are guaranteed to be short-lived.
  int sum(int a, int b) {
    return _sum(a, b);
  }

  late final _sumPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('sum');
  late final _sum = _sumPtr.asFunction<int Function(int, int)>();

  /// A longer lived native function, which occupies the thread calling it.
  ///
  /// Do not call these kind of native functions in the main isolate. They will
  /// block Dart execution. This will cause dropped frames in Flutter applications.
  /// Instead, call these native functions on a separate isolate.
  int sum_long_running(int a, int b) {
    return _sum_long_running(a, b);
  }

  late final _sum_long_runningPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>(
        'sum_long_running',
      );
  late final _sum_long_running = _sum_long_runningPtr
      .asFunction<int Function(int, int)>();

  int load_model(ffi.Pointer<ffi.Char> path) {
    return _load_model(path);
  }

  late final _load_modelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'load_model',
      );
  late final _load_model = _load_modelPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  void init() {
    return _init();
  }

  late final _initPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'init',
  );
  late final _init = _initPtr.asFunction<void Function()>();

  void set_log_callback(
    ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char> message)>
    >
    callback,
  ) {
    return _set_log_callback(callback);
  }

  late final _set_log_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<
              ffi.NativeFunction<
                ffi.Void Function(ffi.Pointer<ffi.Char> message)
              >
            >,
          )
        >
      >('set_log_callback');
  late final _set_log_callback = _set_log_callbackPtr
      .asFunction<
        void Function(
          ffi.Pointer<
            ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char> message)>
          >,
        )
      >();

  /// 保存回调函数指针
  late final ffi.Pointer<LogCallback> _g_log_callback = _lookup<LogCallback>(
    'g_log_callback',
  );

  LogCallback get g_log_callback => _g_log_callback.value;

  set g_log_callback(LogCallback value) => _g_log_callback.value = value;

  /// 修改日志函数使用回调
  void log_func(ffi.Pointer<ffi.Char> message) {
    return _log_func(message);
  }

  late final _log_funcPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'log_func',
      );
  late final _log_func = _log_funcPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();
}

typedef LogCallback = ffi.Pointer<ffi.NativeFunction<LogCallbackFunction>>;
typedef LogCallbackFunction = ffi.Void Function(ffi.Pointer<ffi.Char> message);
typedef DartLogCallbackFunction = void Function(ffi.Pointer<ffi.Char> message);
